// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_s7-2qYNIXWk6abNSbei0W5--nWjOd2Y',
    appId: '1:211607424911:web:1b01d270e99032b5e245fa',
    messagingSenderId: '211607424911',
    projectId: 'mobileproject-9eb7e',
    authDomain: 'mobileproject-9eb7e.firebaseapp.com',
    storageBucket: 'mobileproject-9eb7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3GvN-N3Qb4vqx0_ROcvGxg_XLaT5Oms',
    appId: '1:211607424911:android:d92be7907007c420e245fa',
    messagingSenderId: '211607424911',
    projectId: 'mobileproject-9eb7e',
    storageBucket: 'mobileproject-9eb7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYS3YeavEDFgx7D0qogLyvqp_bcyuPXoI',
    appId: '1:211607424911:ios:915eef2543f77478e245fa',
    messagingSenderId: '211607424911',
    projectId: 'mobileproject-9eb7e',
    storageBucket: 'mobileproject-9eb7e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYS3YeavEDFgx7D0qogLyvqp_bcyuPXoI',
    appId: '1:211607424911:ios:915eef2543f77478e245fa',
    messagingSenderId: '211607424911',
    projectId: 'mobileproject-9eb7e',
    storageBucket: 'mobileproject-9eb7e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_s7-2qYNIXWk6abNSbei0W5--nWjOd2Y',
    appId: '1:211607424911:web:e9831305f9914ebce245fa',
    messagingSenderId: '211607424911',
    projectId: 'mobileproject-9eb7e',
    authDomain: 'mobileproject-9eb7e.firebaseapp.com',
    storageBucket: 'mobileproject-9eb7e.firebasestorage.app',
  );
}
